# Generated by Django 4.2.5 on 2023-12-10 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviewsDjangoApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="userReviews",
            new_name="bds_user_reviews",
        ),
    ]
